## Datos externos - Google Trends

Periodo: 01-01-21 a 30-09-24

Keywords: portabicis, portabicicletas

In [11]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [12]:
trends = pd.read_excel('DatosExternos_Trends.xlsx')

In [13]:
trends

          Week  portabicis  portabicicletas
0   2020-12-27          48               54
1   2021-01-03          35               43
2   2021-01-10          25               29
3   2021-01-17          29               37
4   2021-01-24          32               39
..         ...         ...              ...
192 2024-09-01          32               27
193 2024-09-08          39               38
194 2024-09-15          35               29
195 2024-09-22          34               30
196 2024-09-29          21               28

[197 rows x 3 columns]

In [14]:
trends['interest'] = (trends['portabicis'] + trends['portabicicletas']) / 2

In [15]:
trends

          Week  portabicis  portabicicletas  interest
0   2020-12-27          48               54      51.0
1   2021-01-03          35               43      39.0
2   2021-01-10          25               29      27.0
3   2021-01-17          29               37      33.0
4   2021-01-24          32               39      35.5
..         ...         ...              ...       ...
192 2024-09-01          32               27      29.5
193 2024-09-08          39               38      38.5
194 2024-09-15          35               29      32.0
195 2024-09-22          34               30      32.0
196 2024-09-29          21               28      24.5

[197 rows x 4 columns]

In [16]:
google_trends = trends.drop(columns=['portabicis', 'portabicicletas'])

In [22]:
google_trends

          Week  interest
0   2020-12-27      51.0
1   2021-01-03      39.0
2   2021-01-10      27.0
3   2021-01-17      33.0
4   2021-01-24      35.5
..         ...       ...
192 2024-09-01      29.5
193 2024-09-08      38.5
194 2024-09-15      32.0
195 2024-09-22      32.0
196 2024-09-29      24.5

[197 rows x 2 columns]

In [23]:
google_trends.dtypes

Week        datetime64[ns]
interest           float64
dtype: object