## Datos externos - eventos ciclismo

Real Federacion Española de Turismo: https://rfec.com/index.php/es/smartweb/seccion/calendario/rfec/2022

Periodo: 2021-2024

La idea es que en el input final del modelo haya una columna que se llame 'evento' y haya un 0 si no hay evento y un 1 si si hay evento

In [5]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

In [7]:
eventos21 = pd.read_excel('Calendario Ciclismo 2021.xlsx')
eventos22 = pd.read_excel('Calendario Ciclismo 2022.xlsx')
eventos23 = pd.read_excel('Calendario Ciclismo 2023.xlsx')
eventos24 = pd.read_excel('Calendario Ciclismo 2024.xlsx')

In [9]:
eventos21.head(2)

,Fecha inicio,Fecha fin,Modalidad,Clase,Prueba,Provincia,Lugar,Club,Email,Observaciones,Info,Categorías
0,02/01/2021,02/01/2021,CicloCross,1.33.5,VII CX CIUDAD DE TORRELAVEGA- V MEMORIAL FELIX...,CANTABRIA,TORRELAVEGA,CICLOTURISMO CANTABRIA CLUB,cicloturismocantabria@gmail.com,,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
1,08/01/2021,10/01/2021,CicloCross,1.33.0,CAMPEONATOS DE ESPAÑA DE CICLO CROSS 2021,CANTABRIA,TORRELAVEGA,CANTABRA DE CICLISMO FEDERACION,info@fcciclismo.com,CAMPEONATO DE ESPAÑA CICLOCROSS,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."

In [10]:
eventos22.head(2)

,Fecha inicio,Fecha fin,Modalidad,Clase,Prueba,Provincia,Lugar,Club,Email,Observaciones,Info,Categorías
0,02/01/2022,02/01/2022,CicloCross,1.33.5,BRU-CX CICLOCROSS DEL BRUC,BARCELONA,EL BRUC,ELS CULETS VERMELLS CLUB CICLISTA,elsculetsvermells@gmail.com,,NaN,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
1,02/01/2022,02/01/2022,CicloCross,1.33.5,50 ORMAIZTEGIKO ZIKLO KROSS PROBA-50 PRUEBA CI...,GIPUZKOA,ORMAIZTEGI,ORMAIZTEGIKO T.L.,ormaiztegiko.tx.l@hotmail.com,,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."

In [11]:
eventos23.head(2)

,Fecha inicio,Fecha fin,Modalidad,Clase,Prueba,Provincia,Lugar,Club,Email,Observaciones,Info,Categorías
0,06/01/2023,07/01/2023,Pista,C.2,I GIPUZKOA SARIA NAGUSIA,GIPUZKOA,SAN SEBASTIAN,GIPUZKOAKO TX. FEDERAZIOA,gtxe@gtxe.eus,,NaN,"Elite, Elite fem., Elite UCI, Junior, Junior f..."
1,06/01/2023,08/01/2023,Paralímpico,C2 CA,GIPUZKOA PISTA SARI NAGUSIA,GIPUZKOA,SAN SEBASTIAN,GIPUZKOAKO TX. FEDERAZIOA,gtxe@gtxe.eus,,NaN,Paralímpico

In [13]:
eventos24.head(2)

,Fecha inicio,Fecha fin,Modalidad,Clase,Prueba,Provincia,Lugar,Club,Email,Observaciones,Info,Categorías
0,07/01/2024,07/01/2024,CicloCross,1.33.5,I CICLOCROSS AYUNTAMIENTO DE MAZCUERRAS,CANTABRIA,MAZCUERRAS,LOS 10.000 DEL SOPLAO CLUB DEPORTIVO,info@diezmildelsoplao.com,,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
1,12/01/2024,14/01/2024,CicloCross,1.33.0,CAMPEONATO ESPAÑA CICLOCROSS 2024,ALAVA,AMURRIO,KUSKUMENDI MTB C.D.,kuskumendimtb@gmail.com,CAMPEONATO DE ESPAÑA CICLOCROSS,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."

In [15]:
eventos = pd.concat([eventos21, eventos22, eventos23, eventos24], ignore_index=True)
eventos

,Fecha inicio,Fecha fin,Modalidad,Clase,Prueba,Provincia,Lugar,Club,Email,Observaciones,Info,Categorías
0,02/01/2021,02/01/2021,CicloCross,1.33.5,VII CX CIUDAD DE TORRELAVEGA- V MEMORIAL FELIX...,CANTABRIA,TORRELAVEGA,CICLOTURISMO CANTABRIA CLUB,cicloturismocantabria@gmail.com,,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
1,08/01/2021,10/01/2021,CicloCross,1.33.0,CAMPEONATOS DE ESPAÑA DE CICLO CROSS 2021,CANTABRIA,TORRELAVEGA,CANTABRA DE CICLISMO FEDERACION,info@fcciclismo.com,CAMPEONATO DE ESPAÑA CICLOCROSS,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
2,24/01/2021,24/01/2021,Carretera,1.EUT,CLASSICA COMUNIDAD VALENCIANA 1969 - GRAN PREM...,ALICANTE,VALENCIA,LA MARINA CC,info@cclamarina.org,,NaN,Elite UCI
3,31/01/2021,31/01/2021,Carretera,1.40.5,1ª CURSA SOCIAL DE BELLCAIRE,GIRONA,BELLCAIRE D'EMPORDA,NOU EMPORDA BIKES CLUB CICLISTA,thecoach12@hotmail.com,,NaN,A partir de 17 años
4,06/02/2021,07/02/2021,BMX,1.28.1,COPA ESPAÑA BMX EL CAMPELLO,ALICANTE,EL CAMPELLO,EL CAMPELLO CC,cbmxelcampello@gmail.com,COPA DE ESPAÑA BMX. (SUSPENDIDA),NaN,"Alevin, Alevin Fem., Cadete, Cadete fem., Chal..."
...,...,...,...,...,...,...,...,...,...,...,...,...
3053,28/12/2024,28/12/2024,CicloCross,1.33.5,IV CICLOCROSS CONCELLO DE NIGRAN-ZFV PORTO DO ...,PONTEVEDRA,NIGRAN,CORUXO C.C.,clubciclistacoruxo@hotmail.com,,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
3054,28/12/2024,28/12/2024,CicloCross,1.33.5,"CICLOCROSS ""CIUDAD DEL CICLISMO""",CASTELLON,CERVERA DEL MAESTRE,BENICARLO UC,uniociclistabenicarlo@gmail.com,,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
3055,29/12/2024,29/12/2024,CicloCross,1.33.5,CICLOCROS VILABLAREIX 2024,GIRONA,VILABLAREIX,VILABLAREIX CLUB CICLISTA,btt@ccvilablareix.cat,,NaN,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
3056,29/12/2024,29/12/2024,CicloCross,1.33.5,I CICLOCROSS CIUDAD DE BURRIANA,CASTELLON,BURRIANA,CICLOCLINIC CC,info@cicloclinic.com,,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."
3057,29/12/2024,29/12/2024,CicloCross,1.33.5,V TROFEO CX VILLA DE PARLA,MADRID,PARLA,CIUDAD DE PARLA C.C.,clubciclistaciudaddeparla@gmail.com,,https://rfec.com/index.php/inscripciones/prueb...,"Cadete, Cadete fem., Elite, Elite fem., Elite ..."

In [19]:
eventos_ciclismo = eventos.drop(columns = ['Fecha fin', 'Modalidad','Clase','Prueba', 'Lugar','Provincia','Club','Email', 'Info', 'Categorías','Observaciones'])
eventos_ciclismo

     Fecha inicio
0      02/01/2021
1      08/01/2021
2      24/01/2021
3      31/01/2021
4      06/02/2021
...           ...
3053   28/12/2024
3054   28/12/2024
3055   29/12/2024
3056   29/12/2024
3057   29/12/2024

[3058 rows x 1 columns]

In [21]:
eventos_ciclismo['Evento'] = 1

In [22]:
eventos_ciclismo

     Fecha inicio  Evento
0      02/01/2021       1
1      08/01/2021       1
2      24/01/2021       1
3      31/01/2021       1
4      06/02/2021       1
...           ...     ...
3053   28/12/2024       1
3054   28/12/2024       1
3055   29/12/2024       1
3056   29/12/2024       1
3057   29/12/2024       1

[3058 rows x 2 columns]

In [26]:
eventos_ciclismo.groupby(['Fecha inicio']).agg({'Evento':sum}).reset_index()

    Fecha inicio  Evento
0     01/02/2023       1
1     01/02/2024       1
2     01/04/2021       1
3     01/04/2022       2
4     01/04/2023       9
..           ...     ...
694   31/07/2022       2
695   31/08/2022       1
696   31/08/2024       1
697   31/10/2021       3
698   31/12/2022       1

[699 rows x 2 columns]

*Nota: en el input, en las fechas que no haya evento - poner un 0

In [29]:
eventos_ciclismo.dtypes

Fecha inicio    object
Evento           int64
dtype: object

In [30]:
eventos_ciclismo['Fecha inicio'] = pd.to_datetime(eventos_ciclismo['Fecha inicio'], errors='coerce')

In [31]:
eventos_ciclismo.dtypes

Fecha inicio    datetime64[ns]
Evento                   int64
dtype: object